version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:9.9-stretch
    working_directory: /tmp/my-project
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - run: bash .circleci/setup-heroku.sh
      - run: git push --force dokku@$DOKKU_HOST:jarvis HEAD:refs/heads/master
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
notify:
  webhooks:
    - url: https://jarvis.platform.apodaca.im/circle-ci
