const namedblackcards = ["Why can't $username sleep at night? $whitecard",
	"$username got 99 problems but $whitecard ain't one.",
	"Maybe $username's born with it.  Maybe it's $whitecard.",
	"What ended $username's last relationship? $whitecard",
	"$username drink to forget $whitecard.",
	"$whitecard.  That's how $username want to die.",
	"For $username's next trick, $username will pull $whitecard out of $whitecard.",
	"What does $username prefer? $whitecard",
	"Dear Abby, $username's having some trouble with $whitecard and would like your advice.",
	"During sex, $username like to think about $whitecard.",
	"What are $username's parents hiding from $username? $whitecard",
	"What did $username bring back from Mexico? $whitecard",
	"What will $username bring back in time to convince people that $username am a powerful wizard? $whitecard",
	"How is $username maintaining $username's relationship status? $whitecard",
	"While the United States raced the Soviet Union to the moon, $username funneled millions of pesos into research on $whitecard.",
	"After the earthquake, $username brought $whitecard to the people of Haiti.",
	"But before $username kill you, Mr. Bond, $username must show you $whitecard.",
	"What gives $username uncontrollable gas? $whitecard",
	"What's $username's secret power? $whitecard",
	"$username never truly understood $whitecard until $username encountered $whitecard.",
	"Why is $username sticky? $whitecard",
	"$username do not know with what weapons World War III will be fought, but World War IV will be fought with $whitecard.",
	"Why do $username hurt all over? $whitecard",
	"What is $username giving up for Lent? $whitecard",
	"In $username's final moments, he thought about $whitecard.",
	"When $username am President of the United States, $username will create the Department of $whitecard.",
	"When $username am a billionaire, $username shall erect a 50-foot statue to commemorate $whitecard.",
	"When $username was tripping on acid, $whitecard turned into $whitecard.",
	"That's right, $username killed $whitecard.  How, you ask?  $whitecard.",
	"What's $username's anti-drug? $whitecard",
	"$username's plan for world domination begins with $whitecard.",
	"Dear $username, We regret to inform you that the Office of $whitecard has denied your request for $whitecard",
	"When all else fails, $username can always masturbate to $whitecard.",
	"$username learned the hard way that you can't cheer up a grieving friend with $whitecard.",
	"Next season on Man vs. Wild, $username must survive in the depths of the Amazon with only $whitecard and his wits.",
	"When $username pooped, what came out of their butt? $whitecard",
	"And $username would have gotten away with it, too, if it hadn't been for $whitecard.",
	"During his midlife crisis, $username's dad got really into $whitecard.",
	"Before $username run for president, $username must destroy all evidence of $username's involvement with $whitecard.",
	"$username's mom freaked out when she looked at $username's browser history and found $whitecard.com.",
	"$username went from $whitecard to $whitecard, all thanks to $whitecard.",
	"$username's country, 'tis of thee, sweet land of $whitecard.",
	"$username spent $username's whole life working toward $whitecard, only to have it ruined by $whitecard.",
	"The healing process began when $username joined a support group for victims of $whitecard.",
	"Charades was ruined for $username forever when $username's mom had to act out $whitecard.",
	"Back when $username was 12 and $username was just starting playing D&D, the game had $whitecard.",
	"$username's innovative new RPG has a stat for $whitecard.",
	"For the convention $username cosplayed as Sailor Moon, except with $whitecard.",
	"You evaded $username's $whitecard attack. Most impressive.",
	"$username downloaded a doujin where $whitecard got into $whitecard.",
	"$username's boyfriend's a $whitecard now.",
	"The $whitecard of $whitecard has left $username in despair!",
	"After blacking out during New year's Eve, $username was awoken by $whitecard.",
	"Every Christmas, $username gets drunk and tells the story about $whitecard.",
	"What keeps $username warm during the cold, cold, winter? $whitecard",
	"On the third day of Christmas, $username's true love gave to $username: three French hens, two turtle doves, and $whitecard.",
	"$username is late on his $whitecard.",
	"The best thing $username ever got for Christmas was $whitecard.",
	"$username did $whitecard with the $whitecard!?!",
	"Stop looking at $username $whitecard!",
	"$username's cuckoo for $whitecard puffs.",
	"$username's father gave his life fighting to protect $whitecard from $whitecard.",
	"Why is $username's throat sore? $whitecard",
	"$username is very sorry Mrs. Smith, but Little Billy has tested positive for $whitecard.",
	"When $username was 10 $username wrote to Santa wishing for $whitecard.",
	"Where or How $username met $username's last signifigant other: $whitecard.",
	"$whitecard. This is $username's fetish.",
	"$username did $whitecard so you don't have to!",
	"$username need your clothes, your bike, and $whitecard.",
	"$username's zombie survival kit includes food, water, and $whitecard.",
	"What was the theme of $username's second wedding? $whitecard",
	"$username can only express myself through $whitecard.",
	"$username's new porn DVD was completely ruined by the inclusion of $whitecard",
	"$username's three wishes will be for $whitecard, $whitecard, and $whitecard.",
	"$username got fired because of $username's not-so-secret obsession over $whitecard.",
	"$username's new favourite sexual position is $whitecard",
	"$username's life is ruled by a vicious cycle of $whitecard and $whitecard.",
	"$username's not like the rest of you. $username's too rich and busy for $whitecard.",
	"What left this stain on $username's couch? $whitecard",
	"Money can't buy $username love, but it can buy $username $whitecard.",
	"During high school, $username never really fit in until $username found $whitecard club.",
	"Hey, baby, come back to $username's place and $username'll show you $whitecard.",
	"$username's gym teacher got fired for adding $whitecard to the obstacle course.",
	"Listen, son. If you want to get involved with $whitecard, $username won't stop you. Just steer clear of $whitecard.",
	"$username just met you and this is crazy, but here's $whitecard, so $whitecard maybe",
	"$username's sweating like a $whitecard at a $whitecard.",
	"$username love the smell of $whitecard in the morning.",
	"So $username was $whitecard in $username's cubicle at work, and suddenly $whitecard!",
	"$username can drive and $whitecard at the same time."
];

const answeredblackcards = ["$username?  There's an app for that.",
	"What's that smell? $username",
	"What's the next Happy Meal toy? $username",
	"Anthropologists have recently discovered a primitive tribe that worships $username.",
	"It's a pity that kids these days are all getting involved with $username.",
	"During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of $username.",
	"Alternative medicine is now embracing the curative powers of $username.",
	"What's that sound? $username",
	"MTV's new reality show features eight washed-up celebrities living with $username.",
	"What is Batman's guilty pleasure? $username",
	"This is the way the world ends. This is the way the world ends. Not with a bang but with $username.",
	"What's a girl's best friend? $username",
	"TSA guidelines now prohibit $username on airplanes.",
	"In the new Disney Channel Original Movie, Hannah Montana struggles with $username for the first time.",
	"Instead of coal, Santa now gives the bad children $username.",
	"What's the most emo? $username",
	"In 1,000 years when paper money is but a distant memory, $username will be our currency.",
	"What's the next superhero/sidekick duo? $username",
	"A romantic, candlelit dinner would be incomplete without $username.",
	"$username.  Becha can't have just one!",
	"White people like $username.",
	"$username.  High five, bro.",
	"Next from J.K. Rowling: Harry Potter and the Chamber of $username.",
	"BILLY MAYS HERE FOR $username.",
	"War!  What is it good for? $username",
	"What will always get you laid? $username",
	"In L.A. County Jail, word is you can trade 200 cigarettes for $username.",
	"What don't you want to find in your Chinese food? $username",
	"$username.  It's a trap!",
	"Coming to Broadway this season, $username: The Musical.",
	"Next on ESPN2, the World Series of $username.",
	"What do old people smell like? $username",
	"The class field trip was completely ruined by $username.",
	"When Pharaoh remained unmoved, Moses called down a Plague of $username.",
	"What's there a ton of in heaven? $username",
	"What would grandma find disturbing, yet oddly charming? $username",
	"What did the U.S. airdrop to the children of Afghanistan? $username",
	"What helps Obama unwind? $username",
	"What did Vin Diesel eat for dinner? $username",
	"$username: good to the last drop.",
	"What gets better with age? $username",
	"$username: kid-tested, mother-approved.",
	"What's the crustiest? $username",
	"What's Teach for America using to inspire inner city students to succeed? $username",
	"Studies show that lab rats navigate mazes 50% faster after being exposed to $username.",
	"Life for American Indians was forever changed when the White Man introduced them to $username.",
	"Make a haiku. $username",
	"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on $username.",
	"$username + $username = $username.",
	"What never fails to liven up the party? $username",
	"What's the new fad diet? $username",
	"Major League Baseball has banned $username for giving players an unfair advantage.",
	"The CIA now interrogates enemy agents by repeatedly subjecting them to $username.",
	"In Rome, there are whisperings that the Vatican has a secret room devoted to $username.",
	"Science will never explain $username.",
	"In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated $username.",
	"The socialist governments of Scandinavia have declared that access to $username is a basic human right.",
	"In his new self-produced album, Kanye West raps over the sounds of $username.",
	"What's the gift that keeps on giving? $username",
	"In the distant future, historians will agree that $username marked the beginning of America's decline.",
	"What has been making life difficult at the nudist colony? $username",
	"What brought the orgy to a grinding halt? $username",
	"This is your captain speaking. Fasten your seatbelts and prepare for $username.",
	"In his newest and most difficult stunt, David Blaine must escape from $username.",
	"The Five Stages of Grief: denial, anger, bargaining, $username, and acceptance.",
	"Members of New York's social elite are paying thousands of dollars just to experience $username.",
	"This month's Cosmo: Spice up your sex life by bringing $username into the bedroom.",
	"Little Miss Muffet Sat on a tuffet, Eating her curds and $username.",
	"After months of debate, the Occupy Wall Street General Assembly could only agree on More $username!",
	"Next time on Dr. Phil: How to talk to your child about $username.",
	"Only two things in life are certain: death and $username.",
	"Everyone down on the ground! We don't want to hurt anyone. We're just here for $username.",
	"The votes are in, and the new high school mascot is $username.",
	"Tonight on 20/20: What you don't know about $username could kill you.",
	"D&D 4.0 isn't real D&D because of the $username.",
	"It's a D&D retroclone with $username added.",
	"Storygames aren't RPGs because of the $username.",
	"The Slayer's Guide to $username.",
	"Alightment: Chaotic $username",
	"It's a D&D retroclone with $username added.",
	"What made the paladin fall? $username",
	"The portal leads to the quasi-elemental plane of $username.",
	"The Temple of Elemental $username.",
	"Pathfinder is basically D&D $username Edition.",
	"$username : The Storytelling Game.",
	"People are wondering why Steve Jackson published GURPS $username.",
	"Linear Fighter, Quadratic $username.",
	"You start with 1d4 $username points.",
	"Big Eyes, Small $username.",
	"In the grim darkness of the future there is only $username.",
	"A true gamer has no problem with $username.",
	"The Deck of Many $username.",
	"You are all at a tavern when $username approach you.",
	"The worst part of Grave of the Fireflies is all the $username.",
	"In the Evangelion remake, Shinji has to deal with $username.",
	"Worst anime convention purchase ever? $username.",
	"While powering up Vegeta screamed, $username!",
	"The magical girl found out that the Power of Love is useless against $username.",
	"The Japanese government has spent billions of yen researching $username.",
	"$username is Best Pony.",
	"The $username of Haruhi Suzumiya.",
	"The new thing in Akihabara is fetish cafes where you can see girls dressed up as $username.",
	"Your drill can pierce $username!",
	"Avatar: The Last $username bender.",
	"In the name of $username Sailor Moon will punish you!",
	"No harem anime is complete without $username.",
	"$username.tumblr.com",
	"Somehow they made a cute mascot girl out of $username.",
	"Haruko hit Naoto in the head with her bass guitar and $username came out.",
	"This holiday season, Tim Allen must overcome his fear of $username to save Christmas.",
	"Jesus is $username.",
	"Wake up, America. Christmas is under attack by secular liberals and their $username.",
	"We got the third rope, now where's the fourth? $username",
	"Tackle, Dropdown, $username.",
	"Genius is 10% inspiration, 90% $username.",
	"There's no crying in $username.",
	"Mastodon! Pterodactyl! Triceratops! Sabretooth Tiger! $username!",
	"Don't eat the $username.",
	"SOOOOO hot, want to touch the $username.",
	"Silly rabbit, $username are for kids.",
	"Between love and madness lies $username.",
	"Instead of chess, the Grim Reaper now gambles for your soul with a game of $username.",
	"Instead of beating them, Chris Brown now does $username to women.",
	"Instead of cutting, trendy young emo girls now engage in $username.",
	"The definition of rock bottom is gambling away $username.",
	"The Mayan prophecies really heralded the coming of $username in 2012.",
	"$username, Never leave home without it.",
	"In a new Cold War retro movie, the red menace tries to conquer the world through the cunning use of $username.",
	"In The Hangover part 3, those four guys have to deal with $username, $username, and $username.",
	"The way to a man's heart is through $username.",
	"What's the newest Japanese craze to head West? $username",
	"Everybody loves $username.",
	"The latest horrifying school shooting was inspired by $username.",
	"A successful job interview begins with a firm handshake and ends with $username.",
	"Lovin' you is easy 'cause you're $username.",
	"The blind date was going horribly until we discovered our shared interest in $username.",
	"$username. Awesome in theory, kind of a mess in practice.",
	"In the seventh circle of Hell, sinners must endure $username for all eternity.",
	"Call the law offices of Goldstein & Goldstein, because no one should have to tolerate $username in the workplace.",
	"Turns out that $username-Man was neither the hero we needed nor wanted.",
	"As part of his daily regimen, Anderson Cooper sets aside 15 minutes for $username.",
	"And what did you bring for show and tell? $username",
	"To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of $username.",
	"Finally! A service that delivers $username right to your door.",
	"As part of his contract, Prince won't perform without $username in his dressing room.",
	"It's only $username if you get caught!",
	"$username: The Next Generation",
	"Terminator 4: $username",
	"Disney presents $username on ice!",
	"$username. The other white meat.",
	"You're not gonna believe this, but $username.",
	"$username. All the cool kids are doing it.",
	"Baskin Robbins just added a 32nd flavor: $username!",
	"$username ain't nothin' to fuck wit!"
];

const whitecards = ["Flying sex snakes",
	"Michelle Obama's arms",
	"German dungeon porn",
	"White people",
	"Getting so angry that you pop a boner",
	"Tasteful sideboob",
	"Praying the gay away",
	"Two midgets shitting into a bucket",
	"MechaHitler",
	"Being a motherfucking sorcerer",
	"A disappointing birthday party",
	"Puppies!",
	"A windmill full of corpses",
	"Guys who don't call",
	"Racially-biased SAT questions",
	"Dying",
	"Steven Hawking talking dirty",
	"Being on fire",
	"A lifetime of sadness",
	"An erection that lasts longer than four hours",
	"AIDS",
	"Same-sex ice dancing",
	"Glenn Beck catching his scrotum on a curtain hook",
	"The Rapture",
	"Pterodactyl eggs",
	"Crippling debt",
	"Eugenics",
	"Exchanging pleasantries",
	"Dying of dysentery",
	"Roofies",
	"Getting naked and watching Nickelodeon",
	"The forbidden fruit",
	"Republicans",
	"The Big Bang",
	"Anal beads",
	"Amputees",
	"Men",
	"Surprise sex!",
	"Kim Jong-il",
	"Concealing a boner",
	"Agriculture",
	"Glenn Beck being harried by a swarm of buzzards",
	"Making a pouty face",
	"A salty surprise",
	"The Jews",
	"Charisma",
	"YOU MUST CONSTRUCT ADDITIONAL PYLONS",
	"Panda sex",
	"Taking off your shirt",
	"A drive-by shooting",
	"Ronald Reagan",
	"Morgan Freeman's voice",
	"Breaking out into song and dance",
	"Jewish fraternities",
	"Dead babies",
	"Masturbation",
	"Hormone injections",
	"All-you-can-eat shrimp for $4.99",
	"Incest",
	"Scalping",
	"Soup that is too hot",
	"The Ubermensch",
	"Nazis",
	"Tom Cruise",
	"Stifling a giggle at the mention of Hutus and Tutsis",
	"Edible underpants",
	"The Hustle",
	"A Super Soaker full of cat pee",
	"Figgy pudding",
	"Object permanence",
	"Consultants",
	"Intelligent design",
	"Nocturnal emissions",
	"Uppercuts",
	"Being marginalized",
	"The profoundly handicapped",
	"Obesity",
	"Chutzpah",
	"Unfathomable stupidity",
	"Repression",
	"Attitude",
	"Passable transvestites",
	"Party poopers",
	"The American Dream",
	"Child beauty pageants",
	"Puberty",
	"Testicular torsion",
	"The folly of man",
	"Nickelback",
	"Swooping",
	"Goats eating cans",
	"The KKK",
	"Kamikaze pilots",
	"Horrifying laser hair removal accidents",
	"Adderall",
	"A look-see",
	"Doing the right thing",
	"The taint; the grundle; the fleshy fun-bridge",
	"Lactation",
	"Pabst Blue Ribbon",
	"Powerful thighs",
	"Saxophone solos",
	"The gays",
	"A middle-aged man on roller skates",
	"A foul mouth",
	"The thing that electrocutes your abs",
	"Heteronormativity",
	"Cuddling",
	"Coat hanger abortions",
	"A big hoopla about nothing",
	"Boogers",
	"A hot mess",
	"Raptor attacks",
	"My collection of high-tech sex toys",
	"Fear itself",
	"<i>Bees?</i>",
	"Getting drunk on mouthwash",
	"Sniffing glue",
	"Oversized lollipops",
	"An icepick lobotomy",
	"Being rich",
	"Friends with benefits",
	"Teaching a robot to love",
	"Women's suffrage",
	"Me time",
	"The heart of a child",
	"Smallpox blankets",
	"The clitoris",
	"John Wilkes Booth",
	"The glass ceiling",
	"Sarah Palin",
	"Sexy pillow fights",
	"Yeast",
	"Full frontal nudity",
	"Parting the Red Sea",
	"A Bop It",
	"Michael Jackson",
	"Team-building exercises",
	"Harry Potter erotica",
	"Authentic Mexican cuisine",
	"Frolicking",
	"Sexting",
	"Grandma",
	"Not giving a shit about the Third World",
	"Licking things to claim them as your own",
	"Genghis Khan",
	"The hardworking Mexican",
	"RoboCop",
	"My relationship status",
	"Scrubbing under the folds",
	"Porn Stars",
	"Horse meat",
	"Sunshine and rainbows",
	"Expecting a burp and vomiting on the floor",
	"Barack Obama",
	"Spontaneous human combustion",
	"Natural selection",
	"Mouth herpes",
	"Flash flooding",
	"Goblins",
	"A monkey smoking a cigar",
	"Spectacular abs",
	"A good sniff",
	"Wiping her butt",
	"The Three-Fifths compromise",
	"Pedophiles",
	"Doin' it in the butt",
	"Being fabulous",
	"Mathletes",
	"Wearing underwear inside-out to avoid doing laundry",
	"Nipple blades",
	"An M. Night Shyamalan plot twist",
	"A bag of magic beans",
	"Vigorous jazz hands",
	"A defective condom",
	"Skeletor",
	"Vikings",
	"Leaving an awkward voicemail",
	"Teenage pregnancy",
	"Dead parents",
	"Hot cheese",
	"My sex life",
	"A mopey zoo lion",
	"Assless chaps",
	"Riding off into the sunset",
	"Lance Armstrong's missing testicle",
	"Sweet, sweet vengeance",
	"Genital piercings",
	"Keg stands",
	"Darth Vader",
	"Viagra",
	"Necrophilia",
	"A really cool hat",
	"Toni Morrison's vagina",
	"An Oedipus complex",
	"The Tempur-Pedic Swedish Sleep System",
	"Preteens",
	"Dick fingers",
	"A cooler full of organs",
	"Shapeshifters",
	"The Care Bear Stare",
	"Erectile dysfunction",
	"Keanu Reeves",
	"The Virginia Tech Massacre",
	"The Underground Railroad",
	"The chronic",
	"Queefing",
	"Heartwarming orphans",
	"A thermonuclear detonation",
	"Cheating in the Special Olympics",
	"Tangled Slinkys",
	"A moment of silence",
	"Civilian casualties",
	"Catapults",
	"Sharing needles",
	"Ethnic cleansing",
	"Emotions",
	"Children on leashes",
	"Balls",
	"Homeless people",
	"Eating all of the cookies before the AIDS bake-sale",
	"Old-people smell",
	"Farting and walking away",
	"The inevitable heat death of the universe",
	"The violation of our most basic human rights",
	"Fingering",
	"The placenta",
	"The Rev. Dr. Martin Luther King, Jr",
	"Leprosy",
	"Sperm whales",
	"Multiple stab wounds",
	"Flightless birds",
	"Grave robbing",
	"Home video of Oprah sobbing into a Lean Cuisine",
	"Oompa-Loompas",
	"A murder most foul",
	"Tentacle porn",
	"Daddy issues",
	"Bill Nye the Science Guy",
	"Peeing a little bit",
	"The miracle of childbirth",
	"Tweeting",
	"Another goddamn vampire movie",
	"Britney Spears at 55",
	"New Age music",
	"The Make-A-Wish Foundation",
	"Firing a rifle into the air while balls deep in a squealing hog",
	"Active listening",
	"Nicolas Cage",
	"72 virgins",
	"Stranger danger",
	"Hope",
	"A gassy antelope",
	"BATMAN!!!",
	"Chivalry",
	"Passing a kidney stone",
	"Black people",
	"Natalie Portman",
	"A mime having a stroke",
	"Classist undertones",
	"Sean Penn",
	"A mating display",
	"The Holy Bible",
	"Hot Pockets",
	"A sad handjob",
	"Pulling out",
	"Serfdom",
	"Pixelated bukkake",
	"Dropping a chandelier on your enemies and riding the rope up",
	"Jew-fros",
	"Waiting 'til marriage",
	"Euphoria by Calvin Klein",
	"The World of Warcraft",
	"Lunchables",
	"The Kool-Aid Man",
	"The Trail of Tears",
	"Self-loathing",
	"A falcon with a cap on its head",
	"Historically black colleges",
	"Not reciprocating oral sex",
	"Global warming",
	"Ghosts",
	"World peace",
	"A can of whoop-ass",
	"The Dance of the Sugar Plum Fairy",
	"A zesty breakfast burrito",
	"Switching to Geico",
	"Aaron Burr",
	"Picking up girls at the abortion clinic",
	"Land mines",
	"Former President George W. Bush",
	"Geese",
	"Mutually-assured destruction",
	"College",
	"Date rape",
	"Bling",
	"A gentle caress of the inner thigh",
	"A time travel paradox",
	"Seppuku",
	"Poor life choices",
	"Waking up half-naked in a Denny's parking lot",
	"Italians",
	"GoGurt",
	"Finger painting",
	"Robert Downey, Jr",
	"My soul",
	"Smegma",
	"Embryonic stem cells",
	"The South",
	"Christopher Walken",
	"Gloryholes",
	"Pretending to care",
	"Public ridicule",
	"A tiny horse",
	"Arnold Schwarzenegger",
	"A stray pube",
	"Jerking off into a pool of children's tears",
	"Child abuse",
	"Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts",
	"Menstruation",
	"A sassy black woman",
	"Re-gifting",
	"Penis envy",
	"A sausage festival",
	"Getting really high",
	"Drinking alone",
	"Too much hair gel",
	"Hulk Hogan",
	"Overcompensation",
	"Foreskin",
	"Free samples",
	"Shaquille O'Neal's acting career",
	"Five-Dollar Footlongs",
	"Whipping it out",
	"A snapping turtle biting the tip of your penis",
	"Muhammad (Praise Be Unto Him)",
	"Half-assed foreplay",
	"Dental dams",
	"Being a dick to children",
	"Famine",
	"Chainsaws for hands",
	"A gypsy curse",
	"AXE Body Spray",
	"The Force",
	"Explosions",
	"Cybernetic enhancements",
	"Customer service representatives",
	"White privilege",
	"Gandhi",
	"Road head",
	"God",
	"Poorly-timed Holocaust jokes",
	"8 oz. of sweet Mexican black-tar heroin",
	"Judge Judy",
	"The Little Engine That Could",
	"Altar boys",
	"Mr. Clean, right behind you",
	"Vehicular manslaughter",
	"Dwarf tossing",
	"Friction",
	"Lady Gaga",
	"Scientology",
	"Justin Bieber",
	"A death ray",
	"Vigilante justice",
	"The Pope",
	"A sea of troubles",
	"Alcoholism",
	"Poor people",
	"A fetus",
	"Women in yogurt commercials",
	"Exactly what you'd expect",
	"Flesh-eating bacteria",
	"My genitals",
	"A balanced breakfast",
	"Dick Cheney",
	"Lockjaw",
	"Natural male enhancement",
	"Take-backsies",
	"Winking at old people",
	"Opposable thumbs",
	"Flying sex snakes",
	"Passive-aggressive Post-it notes",
	"Inappropriate yodeling",
	"Golden showers",
	"Racism",
	"Copping a feel",
	"Auschwitz",
	"Elderly Japanese men",
	"Raping and pillaging",
	"Kids with ass cancer",
	"Pictures of boobs",
	"The homosexual agenda",
	"A homoerotic volleyball montage",
	"Sexual tension",
	"Hurricane Katrina",
	"Fiery poops",
	"Science",
	"Dry heaving",
	"Cards Against Humanity",
	"Fancy Feast",
	"A bleached asshole",
	"Lumberjack fantasies",
	"American Gladiators",
	"Autocannibalism",
	"Sean Connery",
	"William Shatner",
	"Domino's Oreo Dessert Pizza",
	"An asymmetric boob job",
	"Centaurs",
	"A micropenis",
	"Asians who aren't good at math",
	"The milk man",
	"Waterboarding",
	"Wifely duties",
	"Loose lips",
	"The Blood of Christ",
	"Actually taking candy from a baby",
	"The token minority",
	"Jibber-jabber",
	"A brain tumor",
	"Bingeing and purging",
	"A clandestine butt scratch",
	"The Chinese gymnastics team",
	"Prancing",
	"The Hamburglar",
	"Police brutality",
	"Man meat",
	"Forgetting the Alamo",
	"Eating the last known bison",
	"Crystal meth",
	"Booby-trapping the house to foil burglars",
	"My inner demons",
	"Third base",
	"Soiling oneself",
	"Laying an egg",
	"Giving 110%",
	"Hot people",
	"Friendly fire",
	"Count Chocula",
	"Pac-Man uncontrollably guzzling cum",
	"Estrogen",
	"My vagina",
	"Kanye West",
	"A robust mongoloid",
	"The Donald Trump Seal of Approval",
	"The true meaning of Christmas",
	"Her Royal Highness, Queen Elizabeth II",
	"An honest cop with nothing left to lose",
	"Feeding Rosie O'Donnell",
	"The Amish",
	"The terrorists",
	"When you fart and a little bit comes out",
	"Pooping back and forth. Forever",
	"Friends who eat all the snacks",
	"Cockfights",
	"Bitches",
	"Seduction",
	"A big black dick",
	"A beached whale",
	"A bloody pacifier",
	"A crappy little hand",
	"A low standard of living",
	"A nuanced critique",
	"Panty raids",
	"A passionate Latino lover",
	"A rival dojo",
	"A web of lies",
	"A woman scorned",
	"Clams",
	"Apologizing",
	"A plunger to the face",
	"Neil Patrick Harris",
	"Beating your wives",
	"Being a dinosaur",
	"Shaft",
	"Bosnian chicken farmers",
	"Nubile slave boys",
	"Carnies",
	"Coughing into a vagina",
	"Suicidal thoughts",
	"The ooze",
	"Deflowering the princess",
	"Dorito breath",
	"Eating an albino",
	"Enormous Scandinavian women",
	"Fabricating statistics",
	"Finding a skeleton",
	"Gandalf",
	"Genetically engineered super-soldiers",
	"George Clooney's musk",
	"Getting abducted by Peter Pan",
	"Getting in her pants, politely",
	"Gladiatorial combat",
	"Clenched butt cheeks",
	"Hipsters",
	"Historical revisionism",
	"Insatiable bloodlust",
	"Jafar",
	"Jean-Claude Van Damme",
	"Just the tip",
	"Mad hacky-sack skills",
	"Leveling up",
	"Literally eating shit",
	"Making the penises kiss",
	"24-hour media coverage",
	"Medieval Times Dinner & Tournament",
	"Moral ambiguity",
	"My machete",
	"One thousand Slim Jims",
	"Ominous background music",
	"Overpowering your father",
	"Stockholm Syndrome",
	"Quiche",
	"Quivering jowls",
	"Revenge fucking",
	"Ripping into a man's chest and pulling out his still-beating heart",
	"Ryan Gosling riding in on a white horse",
	"Santa Claus",
	"Scrotum tickling",
	"Sexual humiliation",
	"Sexy Siamese twins",
	"Saliva",
	"Space muffins",
	"Statistically validated stereotypes",
	"Sudden Poop Explosion Disease",
	"The boners of the elderly",
	"The economy",
	"Syphilitic insanity",
	"The Gulags",
	"The harsh light of day",
	"The hiccups",
	"The shambling corpse of Larry King",
	"The four arms of Vishnu",
	"Being a busy adult with many important things to do",
	"Tripping balls",
	"Words, words, words",
	"Zeus's sexual appetites",
	"A bigger, blacker dick",
	"The mere concept of Applebee's",
	"A sad fat dragon with no friends",
	"Catastrophic urethral trauma",
	"Hillary Clinton's death stare",
	"Existing",
	"A pinata full of scorpions",
	"Mooing",
	"Swiftly achieving orgasm",
	"Daddy's belt",
	"Double penetration",
	"Weapons-grade plutonium",
	"Some really fucked-up shit",
	"Subduing a grizzly bear and making her your wife",
	"Rising from the grave",
	"The mixing of the races",
	"Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes",
	"Scrotal frostbite",
	"All of this blood",
	"Loki, the trickster god",
	"Whining like a little bitch",
	"Pumping out a baby every nine months",
	"Tongue",
	"Finding Waldo",
	"Upgrading homeless people to mobile hotspots",
	"Wearing an octopus for a hat",
	"An unhinged ferris wheel rolling toward the sea",
	"Living in a trashcan",
	"The corporations",
	"A magic hippie love cloud",
	"Fuck Mountain",
	"Survivor's guilt",
	"Me",
	"Getting hilariously gang-banged by the Blue Man Group",
	"Jeff Goldblum",
	"Making a friend",
	"A soulful rendition of Ol' Man River",
	"Intimacy problems",
	"A sweaty, panting leather daddy",
	"Spring break!",
	"Being awesome at sex",
	"Dining with cardboard cutouts of the cast of Friends",
	"Another shot of morphine",
	"Beefin' over turf",
	"A squadron of moles wearing aviator goggles",
	"Bullshit",
	"The Google",
	"Pretty Pretty Princess Dress-Up Board Game",
	"The new Radiohead album",
	"An army of skeletons",
	"A man in yoga pants with a ponytail and feather earrings",
	"Mild autism",
	"Nunchuck moves",
	"Whipping a disobedient slave",
	"An ether-soaked rag",
	"A sweet spaceship",
	"A 55-gallon drum of lube",
	"Special musical guest, Cher",
	"The human body",
	"Boris the Soviet Love Hammer",
	"The grey nutrient broth that sustains Mitt Romney",
	"Tiny nipples",
	"Power",
	"Oncoming traffic",
	"A dollop of sour cream",
	"A slightly shittier parallel universe",
	"My first kill",
	"Graphic violence, adult language, and some sexual content",
	"Fetal alcohol syndrome",
	"The day the birds attacked",
	"One Ring to rule them all",
	"Grandpa's ashes",
	"Basic human decency",
	"A Burmese tiger pit",
	"Death by Steven Seagal",
	"Dragon boobs",
	"Verisimilitude",
	"Dissociated mechanics",
	"Rape",
	"Storygames",
	"Random chargen",
	"RPG.net",
	"Dice inserted somewhere painful",
	"FATAL",
	"Ron Edwards' brain damage",
	"Boob plate armor",
	"Gamer chicks",
	"GNS theory",
	"Drizzt",
	"The entire Palladium Books Megaverse",
	"BadWrongFun",
	"Misogynerds",
	"Cultural Marxism",
	"Pissing on Gary Gygax's grave",
	"Steve Jackson's beard",
	"Natural 20",
	"Rapenards",
	"The Crisis of Treachery",
	"Game balance",
	"Fishmalks",
	"A kick to the dicebags",
	"Bearded dwarven women",
	"Owlbear's tears",
	"Magic missile",
	"THAC0",
	"Bigby's Groping Hands",
	"Drow blackface",
	"Save or die",
	"Swine",
	"The Forge",
	"Healing Surges",
	"Gelatinous Cubes",
	"Total Party Kill",
	"Quoting Monty Python",
	"Dumbed down shit for ADD WoW babies",
	"Mike Mearls",
	"Comeliness",
	"Vampire: The Masquerade",
	"Rifts",
	"The random prostitute table",
	"Dildo of Enlightenment +2",
	"Grognards Against Humanity",
	"Cthulhu",
	"The naked succubus in the Monster Manual",
	"Role-playing and roll-playing",
	"Fun Tyrant",
	"4rries",
	"Martial dailies",
	"Black Tokyo",
	"Killfuck Soulshitter",
	"Cheetoism",
	"Grimdark",
	"Kobolds",
	"Oozemaster",
	"Rocks fall, everyone dies",
	"Maid RPG",
	"Splugorth blind warrior women",
	"Dying during chargen",
	"Slaughtering innocent orc children",
	"Lesbian stripper ninjas",
	"Magical tea party",
	"Grinding levels",
	"Dice animism",
	"White privilege",
	"Githyanki therapy",
	"Amber Diceless Roleplaying",
	"A ratcatcher with a small but vicious dog",
	"Bribing the GM with sexual favors",
	"Eurocentric fantasy",
	"Sacred cows",
	"Gygaxian naturalism",
	"Special snowflakes",
	"Neckbeards",
	"Gazebos",
	"Lorraine Williams",
	"Nude larping",
	"Portable holes",
	"Steampunk bullshit",
	"Dump stats",
	"Ale and whores",
	"Japanese schoolgirl porn",
	"Horny catgirls",
	"Japanese people",
	"Cimo",
	"ZA WARUDO!",
	"40 gigs of lolicon",
	"Goku's hair",
	"Slashfic",
	"Star Gentle Uterus",
	"Naruto headbands",
	"Homestuck troll horns",
	"Hayao Miyazaki",
	"The tsunami",
	"Death Note",
	"Small breasts",
	"Asians being racist against each other",
	"Weeaboo bullshit",
	"Tsundere",
	"Body pillows",
	"A lifelike silicone love doll",
	"Anime figures drenched in jizz",
	"Surprise sex",
	"Yaoi",
	"Girls with glasses",
	"Bronies",
	"Blue and white striped panties",
	"4chan",
	"Hello Kitty vibrator",
	"Finishing attack",
	"Keikaku* *(keikaku means plan)",
	"Hatsune Miku's screams",
	"School swimsuits",
	"Lovingly animated bouncing boobs",
	"Dragon Balls",
	"Zangief's chest hair",
	"DeviantArt",
	"Giant fucking robots",
	"Crossplay",
	"Moeblob",
	"Carl Macek's rotting corpse",
	"My waifu",
	"Voice actress Megumi Hayashibara",
	"Lynn Minmei",
	"Panty shots",
	"Love and Justice",
	"Consensual tentacle rape",
	"Gundam",
	"Captain Bright slapping Amuro",
	"The Wave Undulation Cannon",
	"Having sex in the P.E. equipment shed",
	"Tainted sushi",
	"Shitty eurobeat music",
	"Bad dubbing",
	"Fangirls",
	"Kawaii desu uguu",
	"Futanari",
	"Lesbian schoolgirls",
	"Osamu Tezuka, rolling in his grave forever",
	"FUNimation",
	"Underage cosplayers in bondage gear",
	"Jackie Chan",
	"Exchanging Pocky for sexual favors",
	"Shipping",
	"Chiyo's father",
	"Magikarp",
	"Derpy",
	"Nanoha and her special friend Fate",
	"The marbles from Ramune bottles",
	"Wideface",
	"Spoilers",
	"Man-Faye",
	"Oppai mousepads",
	"Another dimension",
	"Homura sniffing Madoka's panties",
	"Hadouken",
	"Asian ball-jointed dolls",
	"J-list",
	"Childhood friends",
	"Monkey D. Luffy's rubbery cock",
	"Cloud's giant fucking Buster Swords",
	"Taking a dump in Char's helmet",
	"Hentai marathons",
	"Gothic Lolita",
	"Onaholes",
	"Super Saiyan Level 2",
	"Gaia Online",
	"Santa's heavy sack",
	"Clearing a bloody path through Walmart with a scimitar",
	"Another shitty year",
	"Whatever Kwanzaa is supposed to be about",
	"A Christmas stocking full of coleslaw",
	"Elf cum",
	"The tiny, calloused hands of the Chinese children that made this card",
	"Taking down Santa with a surface-to-air missile",
	"Socks",
	"Pretending to be happy",
	"Krampus, the Austrian Christmas monster",
	"The Star Wars Holiday Special",
	"My hot cousin",
	"Mall Santa",
	"Several intertwining love stories featuring Hugh Grant",
	"A Hungry-Man Frozen Christmas Dinner for one",
	"Gift-wrapping a live hamster",
	"Space Jam on VHS",
	"Immaculate conception",
	"Fucking up 'Silent Night' in front of 300 parents",
	"A visually arresting turtleneck",
	"A toxic family environment",
	"Eating an entire snowman",
	"Bumpses",
	"A Vin Gerard H8 X 10",
	"Harry Acropolis",
	"Under the ring",
	"Afa The Wild Samoan",
	"Peanut Butter and Baby sandwiches",
	"Yard Tards",
	"Two girls, one cup",
	"Ugly Mexican Hookers",
	"Duct tape",
	"Sodaj",
	"Steve The Teacher",
	"Jefferee",
	"Autoerotic Asphyxiation",
	"Sonic The Hedgehog",
	"Lotto Money",
	"Jailbait",
	"Prison rape",
	"Two And A Half Men",
	"Anne Frank",
	"Black Santa",
	"Jesus Christ (our lord and saviour)",
	"Farting with your armpits",
	"Poopsicles",
	"Slaughtering innocent children",
	"Sex with vegetables",
	"My gay ex-husband",
	"Accidentally sexting your mom",
	"Tabasco in your pee-hole",
	"Pee Wee Herman",
	"A breath of fresh air",
	"A great big floppy donkey dick",
	"A pyramid scheme",
	"A school bus surrounded by cop cars",
	"A short walk in the desert with shovels",
	"All the boys staring at your chest",
	"An amorous stallion",
	"Being so wet it just slides out of you",
	"Being tarred and feathered",
	"Catching 'em all",
	"Chained to the bed and whipped to orgasmic bliss by a leather-clad woman",
	"Child-bearing hips",
	"Defenestration",
	"Dungeons and/or dragons",
	"Ecco the Dolphin",
	"George Washington riding on a giant eagle",
	"Getting abducted and probed by aliens",
	"Going viral on YouTube",
	"Gushing",
	"Making the baby Jesus cry",
	"More than you can chew",
	"Napalm",
	"Pancake bitches",
	"Playing God with the power of lightning",
	"Playing tonsil-hockey",
	"Racing cheese wheels downhill",
	"Riding the bomb",
	"Settling arguments with dance-offs",
	"Sheer spite",
	"Sinister laughter",
	"SS Girls",
	"Stealing your sister's underwear",
	"Stroking a cat the wrong way",
	"Sucking and blowing",
	"The bullet with your name on it",
	"The entire rest of eternity, spent in fucking Bruges",
	"The oceans rising to reclaim the land",
	"A cocained-fuelled sex orgy heart attack",
	"A cocktail umbrella ",
	"A murder/suicide pact",
	"A squirming mass of kittens",
	"An angry mob with torches and pitchforks",
	"Biting my girlfriend like a vampire during sex",
	"Dropping your pants and saluting",
	"Frankenstein's Monster",
	"Getting a blowjob in a theater",
	"Going full retard",
	"Going slob-slob-slob all over that knob",
	"Leaking implants",
	"Low-flying planes",
	"Monkies flinging their own shit",
	"My robot duplicate",
	"Other people's children",
	"People who can't take a joke. Seriously",
	"Popping a boner during Sex Ed class",
	"Projectile vomiting",
	"Pulling down panties with your teeth",
	"Saying ",
	"Shedding skin like a snake",
	"Shooting Valley Girls for like, saying like all the time. Really",
	"Slow seductive tentacle rape",
	"Talking like a pirate, y'arr!",
	"Tenderly kissing a unicorn's horn",
	"That bastard Jesus!",
	"The last shreads of dignity",
	"The power of friendship",
	"This card intentionally left blank",
	"Throwing water on a braless woman in a white t-shirt",
	"Upskirts",
	"Wasting all your money on hookers and booze",
	"Winning",
	"A foot fetish",
	"A powerful gag reflex",
	"A tight, Asian pussy",
	"Explosive decompression",
	"Extraordinary Rendition",
	"Forgetting the safety word",
	"Greeting Christmas carollers naked",
	"Handcuffs, without the key",
	"Having a drill for a penis",
	"Hot Jailbait Ass",
	"Liposuction gone horrible wrong",
	"My harem of scantily clad women",
	"Nazi Zombie Robot Ninjas",
	"Redneck gypsies",
	"Scissoring",
	"A guy and two robots who won't shut up",
	"A shotgun wedding",
	"Anne Frank's diary",
	"Autoerotic asphyxiation",
	"Blow Up Bianca the Latex Lovedoll",
	"Endlessly tumbling down an up escalator",
	"Fun with nuns",
	"Getting it all over the walls",
	"Holiday Dinner by Jack Daniels",
	"Nailgun fights",
	"Teaching the bitch a lesson",
	"Nazi super science",
	"Making a human centipede",
	"The primal, ball-slapping sex your parents are having right now",
	"A cat video so cute that your eyes roll back and your spine slides out of your anus",
	"Cock",
	"A cop who is also a dog",
	"Dying alone and in pain",
	"Gay aliens",
	"The way white people is",
	"Reverse cowgirl",
	"The Quesadilla Explosion Salad from Chili's",
	"Actually getting shot, for real",
	"Not having sex",
	"Vietnam flashbacks",
	"Running naked through a mall, pissing and shitting everywhere",
	"Nothing",
	"Warm, velvety muppet sex",
	"Self-flagellation",
	"The systematic destruction of an entire people and their way of life",
	"Samuel L. Jackson",
	"A boo-boo",
	"Going around punching people",
	"The entire Internet",
	"Some kind of bird-man",
	"Chugging a lava lamp",
	"Having sex on top of a pizza",
	"Indescribable loneliness",
	"An ass disaster",
	"Shutting the fuck up",
	"All my friends dying",
	"Putting an entire peanut butter and jelly sandwich into the VCR",
	"Spending lots of money",
	"Some douche with an acoustic guitar",
	"Flying robots that kill people",
	"A greased-up Matthew McConaughey",
	"An unstoppable wave of fire ants",
	"Not contributing to society in any meaningful way",
	"An all-midget production of Shakespeare's Richard III",
	"Screaming like a maniac",
	"The moist, demanding chasm of his mouth",
	"Filling every orifice with butterscotch pudding",
	"Unlimited soup, salad, and breadsticks",
	"Crying into the pages of Sylvia Plath",
	"Velcro",
	"A PowerPoint presentation",
	"A surprising amount of hair",
	"Eating Tom Selleck's mustache to gain his powers",
	"Roland the Farter, flatulist to the king",
	"That ass",
	"A pile of squirming bodies",
	"Buying the right pants to be cool",
	"Blood farts",
	"Three months in the hole",
	"A botched circumcision",
	"The Land of Chocolate",
	"Slapping a racist old lady",
	"A lamprey swimming up the toilet and latching onto your taint",
	"Jumping out at people",
	"A black male in his early 20s, last seen wearing a hoodie",
	"Mufasa's death scene",
	"Bill Clinton, naked on a bearskin rug with a saxophone",
	"Demonic possession",
	"The Harlem Globetrotters",
	"Vomiting mid-blowjob",
	"My manservant, Claude",
	"Having shotguns for legs",
	"Letting everyone down",
	"A spontaneous conga line",
	"A vagina that leads to another dimension",
	"Disco fever",
	"Getting your dick stuck in a Chinese finger trap with another dick",
	"Fisting",
	"The thin veneer of situational causality that underlies porn",
	"Girls that always be textin'",
	"Blowing some dudes in an alley",
	"Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy",
	"Sneezing, farting, and coming at the same time",
	"A freshly-filled diaper",
	"Glue",
	"An unusually-attractive transvestite",
	"Hand-me-down adult diapers",
	"A stillborn fetus",
	"A disgraced pelican",
	"Three buckets of urine, free for 2 nights, with no late fee",
	"My testicles",
	"A black woman's vagina",
	"My asshole",
	"A whale's blowhole",
	"2 Girls 1 Cup",
	"The Big Bang Theory (TV)",
	"Teen pregnancy",
	"Ass hair",
	"Vaginal warts",
	"Ellen Degeneres",
	"Jews Against Humanity",
	"Indy wrestling",
	"Cunt",
	"Beating a crowd of delightful parents to death with a steel dildo",
	"Beating a crowd of delightful parents to death with a steel dildo while dressed as Ru Paul's brother, Ron",
	"A roll in the hay",
	"God Hates You",
	"Manboobs",
	"Daniel Benoit",
	"Vomiting in the shower",
	"An intellectually superior overlord",
	"Dwight Schrute",
	"Casey Anthony",
	"Clubbin seals",
	"Stunt cock",
	"Anal lice",
	"Lightsaber Dildos"
];

var random = function(somearray) {
	return somearray[Math.floor(Math.random() * somearray.length)];
}

var whitecard = function() {
	return random(whitecards);
}

module.exports = function(robot) {
	return robot.respond(/rando ?(.*)?/i, function(msg) {
		const username = msg.match[1]? msg.match[1] : random(["Jarvis", "Meatbag", "Rando", "Alex's mom"]);
		const blackcard = random([true, false])? random(namedblackcards) : random(answeredblackcards);
		const answer = blackcard.replace(/\$username/g,username).replace('$whitecard', whitecard()).replace('$whitecard', whitecard()).replace('$whitecard', whitecard());
		return msg.send(answer);
	});
};
